---
- name: "Hyprland | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: hyprland_distribution_config

- name: "Hyprland | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: hyprland_distribution_config.stat.exists

- name: "Hyprland | Check if config folder is a symlink"
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.config/hypr"
  register: hyprland_config_stat

- name: "Hyprland | Remove existing config folder if not a symlink"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/hypr"
    state: absent
  when: not hyprland_config_stat.stat.islnk

- name: "Hyprland | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/hypr"
    state: directory

- name: "Hyprland | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/hypr"
    state: link
    force: true
