---
# Include Tasks
- name: "Timeshift | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"

# Configure Sudoers for Timeshift and Timeshift-GTK
- name: "Configure sudoers to allow timeshift commands without a password"
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/{{ item.file }}"
    state: present
    create: true
    line: "{{ ansible_env.USER }} ALL=(ALL) NOPASSWD: {{ item.command }}"
    validate: "visudo -cf %s"
  loop:
    - file: "timeshift"
      command: "/usr/bin/timeshift"
    - file: "timeshift-gtk"
      command: "/usr/bin/timeshift-gtk"

# Grub-Btrfs Service Configuration
- name: "Grub-Btrfs | Enable and Start Grub-Btrfsd Service"
  ansible.builtin.systemd:
    name: "grub-btrfsd"
    enabled: true
    state: started
  become: true

- name: "Grub-Btrfs | Modify Grub-Btrfsd Service File"
  ansible.builtin.lineinfile:
    path: "/etc/systemd/system/grub-btrfsd.service"
    regexp: "^ExecStart=/usr/bin/grub-btrfsd --syslog"
    line: "ExecStart=/usr/bin/grub-btrfsd --syslog --timeshift-auto"
  become: true
  register: grub_btrfs_service

- name: "Grub-Btrfs | Reload and Restart Grub-Btrfsd Service if Modified"
  ansible.builtin.systemd:
    name: "grub-btrfsd"
    daemon_reload: true
    state: restarted
  become: true
  when: grub_btrfs_service.changed

# Timeshift Configuration
- name: "Timeshift | Check if {{ timeshift_config_file }} is a Symlink"
  ansible.builtin.stat:
    path: "{{ timeshift_config_file }}"
  register: timeshift_config_stat

- name: "Timeshift | Remove Existing {{ timeshift_config_file }} if Not a Symlink"
  ansible.builtin.file:
    path: "{{ timeshift_config_file }}"
    state: absent
  when: timeshift_config_stat.stat.exists and not timeshift_config_stat.stat.islnk
  become: true

- name: "Timeshift | Ensure role path directory exists"
  ansible.builtin.file:
    path: "{{ role_path }}/files"
    state: directory

- name: "Timeshift | Create Symlink to Role Files Directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files/timeshift.json"
    dest: "{{ timeshift_config_file }}"
    state: link
    force: true
  become: true

- name: "Timeshift | Set Correct Permissions for {{ timeshift_config_file }}"
  ansible.builtin.file:
    path: "{{ timeshift_config_file }}"
    owner: "root"
    group: "root"
    mode: "0644"
  become: true
