---
- name: "Steam | {{ ansible_distribution }} | Install steam with pacman"
  become: true
  ansible.builtin.pacman:
    name:
      - steam
    state: present

- name: "Steam | {{ ansible_distribution }} | Install xone (xbox controller)"
  kewlfft.aur.aur:
    name:
      - xone-dkms-git
    state: present
