---
- name: "Python | {{ ansible_distribution }} | Install Python and packages"
  ansible.builtin.pacman:
    name:
      - python
      - python-capng
      - python-defusedxml
      - python-packaging
      - python-pip
      - python-pyqt5
      - python-pyquery
      - python-requests
      - python-watchdog
    state: present
  become: true

- name: "Python | {{ ansible_distribution }} | Install quarto and jupytext"
  kewlfft.aur.aur:
    name:
      - quarto-cli-bin
      - python-jupytext
    state: present

- name: "Python | {{ ansible_distribution }} | Install anaconda"
  kewlfft.aur.aur:
    name: "anaconda"
    state: present
