---
- name: "Btrbk | {{ ansible_distribution }} | Install btrbk"
  ansible.builtin.pacman:
    name: "btrbk"
    state: present
  become: true

- name: "Btrbk | {{ ansible_distribution }} | Install mbuffer"
  ansible.builtin.pacman:
    name: "mbuffer"
    state: present
  become: true

- name: "Restic | {{ ansible_distribution }} | Install restic"
  ansible.builtin.pacman:
    name: "restic"
    state: present
  become: true
