---
- name: "Nvidia | {{ ansible_distribution }} | Install Nvidia with pacman"
  ansible.builtin.pacman:
    name:
      - nvidia
      - nvidia-utils
      - libva-nvidia-driver
      - nvidia-container-toolkit
      - nvidia-settings
    state: present
  become: true
