---
- name: "Nvidia | {{ ansible_distribution }} | Install Nvidia with pacman"
  become: true
  ansible.builtin.pacman:
    name:
      - nvidia-dkms
      - nvidia-utils
      - libva-nvidia-driver
      - nvidia-container-toolkit
      - nvidia-settings
    state: present

- name: "Nvidia | {{ ansible_distribution }} | Check if nvidia.conf exists in /etc/modprobe.d/"
  ansible.builtin.stat:
    path: "/etc/modprobe.d/nvidia.conf"
  register: nvidia_conf_stat
  become: true

- name: "Nvidia | {{ ansible_distribution }} | Remove existing nvidia.conf if it is not a symlink"
  ansible.builtin.file:
    path: "/etc/modprobe.d/nvidia.conf"
    state: absent
  when: not nvidia_conf_stat.stat.islnk
  become: true

- name: "Nvidia | {{ ansible_distribution }} | Create symlink for nvidia.conf"
  ansible.builtin.file:
    src: "{{ role_path }}/files/nvidia.conf"
    dest: "/etc/modprobe.d/nvidia.conf"
    state: link
    force: true
    mode: "0644"
    owner: "root"
    group: "root"
  become: true

- name: "Nvidia | {{ ansible_distribution }} | Install python-pynvml"
  kewlfft.aur.aur:
    name: "python-pynvml"
    state: present
  become: true

- name: "Nvidia | {{ ansible_distribution }} | Copy gpu_fan_control.py to /usr/local/bin"
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/gpu_fan_control.py"
    dest: /usr/local/bin/gpu_fan_control.py
    mode: "0755"
    owner: "root"
    group: "root"

- name: "Nvidia | {{ ansible_distribution }} | Create systemd service file for GPU Fan Control"
  become: true
  ansible.builtin.template:
    src: "{{ role_path }}/files/gpu_fan_control.service.j2"
    dest: /etc/systemd/system/gpu_fan_control.service
    mode: "0644"
    owner: "root"
    group: "root"
  vars:
    gpu_name: "3080"
    min_temp: 30
    min_speed: 10
    max_temp: 85
    max_speed: 100
    interval: 1
    log_file: "/var/tmp/gpu_fan_speed.log"

- name: "Nvidia | {{ ansible_distribution }} | Reload systemd daemon"
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: "Nvidia | {{ ansible_distribution }} | Enable and start GPU Fan Control service"
  become: true
  ansible.builtin.systemd:
    name: gpu_fan_control.service
    enabled: true
    state: started
