---
- name: "Xpipe | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: xpipe_distribution_config

- name: "Xpipe | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: xpipe_distribution_config.stat.exists

- name: "Xpipe | Check if config folder is a symlink"
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.xpipe/settings"
  register: xpipe_config_stat

- name: "Xpipe | Remove existing config folder if not a symlink"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.xpipe/settings"
    state: absent
  when: xpipe_config_stat.stat.exists and not xpipe_config_stat.stat.islnk

- name: "Xpipe | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.xpipe/settings"
    state: directory

- name: "Xpipe | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.xpipe/settings"
    state: link
    force: true
