---
- name: "Waybar | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: waybar_distribution_config

- name: "Waybar | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: waybar_distribution_config.stat.exists

- name: "Waybar | Check if config folder is a symlink"
  ansible.builtin.stat:
    path: "{{ waybar_config_dir }}"
  register: waybar_config_stat

- name: "Waybar | Remove existing config folder if not a symlink"
  ansible.builtin.file:
    path: "{{ waybar_config_dir }}"
    state: absent
  when: waybar_config_stat.stat.exists and not waybar_config_stat.stat.islnk

- name: "Waybar | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ waybar_config_dir }}"

    state: directory

- name: "Waybar | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ waybar_config_dir }}"
    state: link
    force: true
