---
- name: "AMD | {{ ansible_distribution }} | Install AMD-related packages"
  ansible.builtin.pacman:
    name:
      - lib32-mesa
      - vulkan-radeon
      - lib32-vulkan-radeon
      - vulkan-icd-loader
      - lib32-vulkan-icd-loader
    state: present
    update_cache: true
  become: true

- name: "AMD | {{ ansible_distribution }} | Install amdgpu_top from AUR"
  kewlfft.aur.aur:
    name: amdgpu_top
    state: present
