---
- name: "Latex | {{ ansible_distribution }} | Install latex-mk "
  kewlfft.aur.aur:
    name: "texlive-binextra"
    state: present
- name: "Latex | {{ ansible_distribution }} | Install latexrun-git"
  kewlfft.aur.aur:
    name: "latexrun-git"
    state: present
- name: "Latex | {{ ansible_distribution }} | Install zathura "
  kewlfft.aur.aur:
    name: "zathura"
    state: present
- name: "Latex | {{ ansible_distribution }} | Install zathura-pdf-poppler "
  kewlfft.aur.aur:
    name: "zathura-pdf-poppler"
    state: present
- name: "Latex | {{ ansible_distribution }} | Install texlive-fontsextra"
  ansible.builtin.pacman:
    name: "texlive-fontsextra"
    state: present
  become: true
- name: "Latex | {{ ansible_distribution }} | Install texlive-xetex"
  ansible.builtin.pacman:
    name: "texlive-xetex"
    state: present
  become: true
