---
- name: "Neovim | {{ ansible_distribution }} | Install Neovim "
  kewlfft.aur.aur:
    name: "neovim"
    state: present
    update_cache: yes

- name: "Neovim | {{ ansible_distribution }} | Install base-devel "
  kewlfft.aur.aur:
    name: "base-devel"
    state: present

- name: "Neovim | {{ ansible_distribution }} | Install ripgrep "
  kewlfft.aur.aur:
    name: "ripgrep"
    state: present

- name: "Neovim | {{ ansible_distribution }} | Install luarocks "
  kewlfft.aur.aur:
    name: "luarocks"
    state: present

- name: "Neovim | {{ ansible_distribution }} | Install lua51 "
  kewlfft.aur.aur:
    name: "lua51"
    state: present

- name: "Neovim | {{ ansible_distribution }} | Install fd "
  kewlfft.aur.aur:
    name: "fd"
    state: present

- name: "Neovim | {{ ansible_distribution }} | Install tree-sitter-cli "
  kewlfft.aur.aur:
    name: tree-sitter-cli"
    state: present
