---
- name: "Neovim | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: neovim_distribution_config

- name: "Neovim | Run Distribution-Specific Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: neovim_distribution_config.stat.exists

- name: "Neovim | Check if config folder is a symlink"
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.config/nvim"
  register: neovim_config_stat

- name: "Neovim | Remove existing config folder if not a symlink"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: absent
  when: neovim_config_stat.stat.exists and not neovim_config_stat.stat.islnk

- name: "Neovim | Ensure config folder exists or is a symlink"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: absent
  when: neovim_config_stat.stat.exists and not neovim_config_stat.stat.islnk

- name: "Neovim | Create symlink for config folder"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    state: link
    force: true
