services:
  ollama:
    image: ollama/ollama:rocm
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    environment:
      - HSA_OVERRIDE_GFX_VERSION=11.0.0  # Specific to RDNA3/7900 XTX (gfx1100)
    group_add:
      - video

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    # - WEBUI_AUTH=False
    depends_on:
      - ollama

volumes:
  ollama:
  open-webui:
